# serviceattachemnt for istio-ingressgateway-private service
apiVersion: networking.gke.io/v1
kind: ServiceAttachment
metadata:
 name: istio-ingressgateway-private
 namespace: istio-ingressgateway-private
spec:
 connectionPreference: ACCEPT_MANUAL
 # psc subnet name
 natSubnets:
 - psc-ingressgateway-private-subnetwork
 proxyProtocol: false
 resourceRef:
   kind: Service
   name: istio-ingressgateway-private